import {Navigate,NavLink,Route,Routes} from 'react-router-dom';
import {useAuth} from './auth';
import Dashboard from './Dashboard';
import Settings from './Settings';
import Billing from './Billing';
import Admin from './Admin';
import AiStatus,{AiModeToggle} from './AiStatus';

function BrandLogo({login=false}:{login?:boolean}){return <img className={`brand-logo${login?' brand-logo--login':''}`} src={login?'/traxion-logo-completo.webp':'/traxion-ai-copy-trading-logo.webp'} alt={login?'TRAXION — Hyperliquid AI Trading Agent':'TRAXION'} width={login?1672:2048} height={login?941:682} decoding="async"/>}
function Gate({children,admin=false}:{children:React.ReactNode;admin?:boolean}){const {user,loading}=useAuth();if(loading)return <div className="center">Caricamento…</div>;if(!user)return <Navigate to="/login" replace/>;if(admin&&!['ADMIN','SUPERADMIN'].includes(user.role))return <Navigate to="/" replace/>;return <>{children}</>}
function Login(){const {user,signIn,error,loading}=useAuth();if(user)return <Navigate to="/" replace/>;return <main className="login"><section className="panel loginbox"><BrandLogo login/><h1>Trading ibrido. Analisti + AI. Esecuzione automatizzata.</h1><p>TRAXION applica sul tuo account Hyperliquid una strategia operativa sviluppata con analisi umana e sistemi di intelligenza artificiale, con Risk Engine e controlli verificabili.</p><p>Firma un messaggio gratuito per autenticarti. La firma non invia transazioni, non consuma gas e non autorizza TRAXION a muovere fondi. Dopo l’accesso, la sessione viene rinnovata automaticamente fino a 24 ore.</p>{error&&<div className="alert error">{error}</div>}<button className="primary" disabled={loading} onClick={()=>void signIn()}>{loading?'Connessione…':'Connetti wallet'}</button></section></main>}
function Shell(){const {user,signOut}=useAuth();return <div><header><BrandLogo/><nav><NavLink to="/">Dashboard</NavLink><NavLink to="/settings">Configurazione</NavLink><NavLink to="/billing">Piano</NavLink>{user&&['ADMIN','SUPERADMIN'].includes(user.role)&&<NavLink to="/admin">Control room</NavLink>}</nav><div style={{display:'flex',alignItems:'center',gap:10}}><AiModeToggle/><AiStatus/><button onClick={()=>void signOut()}>Esci</button></div></header><div className="wrap"><Routes><Route index element={<Dashboard/>}/><Route path="settings" element={<Settings/>}/><Route path="billing" element={<Billing/>}/><Route path="admin" element={<Gate admin><Admin/></Gate>}/></Routes></div></div>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/*" element={<Gate><Shell/></Gate>}/></Routes>}
